import csv
from typing import Iterator,Dict


"""
    Reads a CSV file and yields each row as a dictionary.
"""

def stream_csv(file_path:str) -> Iterator[Dict[str,str]]:
    """
        Here we will stream the rows one by one 
        instead of loading the entire file into memory.
        We are trying to simulate a real time raw data streaming or generated by acutal producer system.

        Args: 
            file_path (str): Path to the CSV file.
            Yields:a dictionary for each row in the CSV file.ß
    """
    ## using generator to yield one row at a time
    with open(file_path, mode='r') as f:
        reader=csv.DictReader(f)
        for row in reader:
            yield row 
            print(f"Yielded row: {row}")  ## for debugging purpose to see the rows being yielded


if __name__=="__main__":
    ## test the stream_csv function
    file_path="../data/ZomatoDataset.csv"
    for row in stream_csv(file_path):
        pass  ## just to trigger the generator and see the print statements